version: 3
services:
  web:
    image: railway/python:3.9
    env:
      DATABASE_URL: sqlite:///db.sqlite3
    scripts:
      - python -m pip install --upgrade pip
      - python -m pip install -r requirements.txt
      - python manage.py migrate
      - python manage.py collectstatic --no-input
      - python manage.py runserver 0.0.0.0:8080
