# Generated by Django 4.1.1 on 2023-11-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autograder", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="clues_to_autograder",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="comment",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="marks",
            field=models.IntegerField(blank=True),
        ),
    ]
