# Generated by Django 4.1.1 on 2023-12-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autograder", "0006_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subject",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
