# Generated by Django 3.2.20 on 2023-12-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autograder', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='submission_images/'),
        ),
    ]
