# Generated by Django 4.1.1 on 2023-12-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autograder", "0007_submission_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
