# Generated by Django 4.1.1 on 2023-12-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autograder", "0008_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=255),
        ),
    ]
